name: Python package to testpypi
on:
  push:
    tags:
      - "v*.*.*-*"
  workflow_dispatch:
    # inputs:
    #   tag:
    #     description: "Tag to publish"
    #     required: true
    #     default: "v*.*.*-*"
jobs:
  publish_pypi:
    runs-on: ubuntu-latest
    # environment: release    
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Mint token
        id: mint
        uses: tschm/token-mint-action@v1.0.2

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ steps.mint.outputs.api-token }}